version: '3'

services:


  nextjs:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    container_name: nextjs
    ports:
      - 5000:5000
    volumes: 
      - .:/srv/app
    tty: true
    